import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxStoreProvider from "@/components/providers/redux-store-provider";
import { MOdalProvider } from "@/components/providers/modal-provider";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxStoreProvider>
            <MOdalProvider />
            {children}
          </ReduxStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
